config/routes.rb
Rails.application.routes.draw do
  resources :parts
  resources :assemblies

   

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :teams
  root 'teams#show'

  resources :employees

		resources :teams do
			member do
			get 'show'
		end
	end
	resources :posts,:comments, module: "admin"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :Employee

	#default_scope lambda { order('articles.title') }
	scope :noemp, lambda {where("articles.Employee_id != 2")}
	scope :emp, lambda {where("articles.Employee_id = 1")}
	scope :fnd,->(title){where(:title=>title.chomp)}
	
	def long_title
	puts"Please Enter Title Name you want to search"
	title=gets()
	Article.fnd(title)
	end
	
end

app/models/assembly.rb
class Assembly < ActiveRecord::Base
	has_and_belongs_to_many :parts
end

app/models/employee.rb
class Employee < ActiveRecord::Base
require 'carrierwave/orm/activerecord'

mount_uploader :avatar, AvatarUploader

	paginates_per 10
	before_validation :check
	before_create :verify_name
	#attr_accessor :emp_name, :emp_des
	validates_presence_of :emp_name,:emp_des, :message =>"can't be empty"
	has_one :Profile
	has_many :Article
private
	def ring
		puts"hello before save method called "
	end

	private
def check
# Strip everything in the number except digits

Date.today
end
private
def verify_name
	#debugger
	@employee = Employee.exists?(emp_name: "#{emp_name}")
	if(@employee)
		
			puts 'root' 
	end	
	#@employee =Employee.all
	#return @employee
end


end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_for_oauth(auth)
    find_or_create_by(uid: auth.uid, provider: auth.provider)
  end
end

app/models/member.rb
class Member < ActiveRecord::Base
has_belongs_to_many :team  #, touch: true
end

app/models/part.rb
class Part < ActiveRecord::Base
has_and_belongs_to_many :assemblies
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :Employee
end

app/models/team.rb
class Team < ActiveRecord::Base
has_and_belongs_to_many :members


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable, :lockable,
  #        :recoverable, :rememberable, :trackable,:confirmable, :validatable

#devise :omniauthable, :omniauth_providers => [:facebook]

devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
     :omniauthable, :omniauth_providers => [:digitalocean]

  def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
      end
  end
    
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
#before_action :verify, :only =>:index
#before_save :ding
#around_filter :new
before_action :authenticate_user!
  def index
  	@employees=Employee.all
  	@employee = @employees.order(:emp_name).page params[:page]  # used for kaminari gem
		
  end

  def new
  	

  	@employee=Employee.new

  end
  def create
  	@employee=Employee.new(employee_params)
  	if (@employee.save)
  		redirect_to employee_path(@employee)
  	
  else
  	render "new"
  end
  end

  def show
  	@employee=Employee.find(params[:id])
  	respond_to do |format|
      format.html

  end
  end

  def destroy
  	@emp=Employee.find(params[:id])
  	@emp.destroy
  	respond_to do |format|
  		format.html{redirect_to employees_path}
  	end
  end

  def edit
  	
  	@employee=Employee.find(params[:id])
  end
 def update
 	@employee =Employee.find(params[:id])
 	if (@employee.update(employee_params))
  		respond_to do |format|
  		format.html{redirect_to employees_path}
  	end
  	end
end
private
def employee_params
  	params.require(:employee).permit(:emp_name,:emp_des,:avatar)
  end

 def verify
 	if (@employee==nil)
 		redirect_to new_employee_path
 	else
 		respond_to do |format|
  		format.html{redirect_to employees_path}
  	end
  end

 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assemblies_helper.rb
module AssembliesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/member_helper.rb
module MemberHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/employees/_employee.html.erb
<link rel="stylesheet" href="/assets/theme.default.css">
<!-- load jQuery and tablesorter scripts -->
<script type="text/javascript" src="/assets/jquery-latest.js"></script>
<script type="text/javascript" src="/assets/jquery.tablesorter.js"></script>
	
<!-- tablesorter widgets (optional) -->




<h1>Employees#index</h1>
<div>
<%= link_to 'Go Back to Team ', '/' %>
<table id="myTable" class ="tablesorter">

<thead><tr><th>Employee Name </th><th>Employee Designation </th><th>Employee Image </th></tr></thead>
<tbody>
<% @employee.each do |emp| %>
<tr>
<td><%= emp.emp_name %></td><td><%= emp.emp_des %></td><td><%= image_tag(emp.avatar,height: '200', width: '250') %></td><td><%= link_to 'Delete',employee_path(emp),:method=> :delete%></td><td><%= link_to 'Edit',edit_employee_path(emp) %></td>
</tr>
<% end %>
</tbody>
</table>
<%= paginate @employee, :left => 1, :right => 3 %>
</div>
<p>Find me in app/views/employees/index.html.erb</p>





<script type='text/javascript'>
    $(document).ready(function() { 
        $("#myTable").tablesorter({ 
            //for example we want to disable the 
            //password column (5th column) from sorting
            //we will specify '4' since it was indexed
            //(count starts at '0')
            //and set its property to 'false'
            headers: { 
                1: {    
                    sorter: false 
                }
            }
              
        }); 
    });
</script>

app/views/employees/_index.html.erb
<link rel="stylesheet" href="/assets/theme.default.css">
<!-- load jQuery and tablesorter scripts -->
<script type="text/javascript" src="/assets/jquery-latest.js"></script>
<script type="text/javascript" src="/assets/jquery.tablesorter.js"></script>
	
<!-- tablesorter widgets (optional) -->




<h1>Employees#index</h1>
<div>
<%= link_to 'Go Back to Team ', '/' %>
<table id="myTable" class ="tablesorter">

<thead><tr><th>Employee Name </th><th>Employee Designation </th><th>Employee Image </th></tr></thead>
<tbody>
<% @employee.each do |emp| %>
<tr>
<td><%= emp.emp_name %></td><td><%= emp.emp_des %></td><td><%= image_tag(emp.avatar,height: '200', width: '250') %></td><td><%= link_to 'Delete',employee_path(emp),:method=> :delete%></td><td><%= link_to 'Edit',edit_employee_path(emp) %></td>
</tr>
<% end %>
</tbody>
</table>
<%= paginate @employee, :left => 1, :right => 3 %>
</div>
<p>Find me in app/views/employees/index.html.erb</p>





<script type='text/javascript'>
    $(document).ready(function() { 
        $("#myTable").tablesorter({ 
            //for example we want to disable the 
            //password column (5th column) from sorting
            //we will specify '4' since it was indexed
            //(count starts at '0')
            //and set its property to 'false'
            headers: { 
                1: {    
                    sorter: false 
                }
            }
              
        }); 
    });
</script>

app/views/employees/edit.html.erb
<h1>Employees#edit</h1>
<%= form_for @employee,url: {action: "update"} do |emp| %>
<p>Emp name: <%= emp.text_field :emp_name%></p>
<p>Emp Designation: <%= emp.text_field :emp_des %></p>
<%= image_tag(:avatar,height: '200', width: '250') %>
<%= emp.file_field :avatar %>
<%= emp.submit 'update' %>
<%= link_to 'See All', employees_path %>
<% end %>


<p>Find me in app/views/employees/edit.html.erb</p>

app/views/employees/index.js.erb
$("#employees").html("<%= escape_javascript(render 'index') %>")

app/views/employees/new.html.erb
<h1>Employees#new</h1>


<% if user_signed_in? %>
	<li>Hello  welcome <%= current_user.email %> </li>
	  <li>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>
  </li>

<%end%>




<%= form_for @employee,url: {action: "create"},:html => {:multipart => true} do |f| %>
<% if @employee.errors.any? %>
<ul>
<% @employee.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<%end%>
<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>
</ul>
<%end%>
<p> Employee Name: <br />  <%= f.text_field :emp_name %></p>
<p>  Employee Designation:<br /><%= f.text_field :emp_des %></p>
<p>
    <label>My Avatar</label>
    <%= image_tag(@employee.avatar_url) if @employee.avatar? %>
    <%= f.file_field :avatar %>
    <%= f.hidden_field :avatar_cache %>
  </p>
<p><%= f.submit 'Submit' %></p><%= link_to 'Back' , root_path %>

<% end %>

<p>Find me in app/views/employees/new.html.erb</p>

app/views/employees/show.html.erb
<h1>Employees#show</h1>

<p>Emp name: <%= @employee.emp_name %></p>
<p>Emp Designation: <%= @employee.emp_des %></p>
<p>Emp Designation: <%= @employee.avatar %></p>
<p><%= image_tag(@employee.avatar,height: '200', width: '250') %></p>
<%= link_to 'See All', employees_path %>
<%= link_to 'Back', new_employee_path %>
<p>Find me in app/views/employees/show.html.erb</p>