config/routes.rb
Rails.application.routes.draw do
  resources :parts
  resources :assemblies

   

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :teams
  root 'teams#show'

  resources :employees

		resources :teams do
			member do
			get 'show'
		end
	end
	resources :posts,:comments, module: "admin"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :Employee

	#default_scope lambda { order('articles.title') }
	scope :noemp, lambda {where("articles.Employee_id != 2")}
	scope :emp, lambda {where("articles.Employee_id = 1")}
	scope :fnd,->(title){where(:title=>title.chomp)}
	
	def long_title
	puts"Please Enter Title Name you want to search"
	title=gets()
	Article.fnd(title)
	end
	
end

app/models/assembly.rb
class Assembly < ActiveRecord::Base
	has_and_belongs_to_many :parts
end

app/models/employee.rb
class Employee < ActiveRecord::Base
require 'carrierwave/orm/activerecord'

mount_uploader :avatar, AvatarUploader

	paginates_per 10
	before_validation :check
	before_create :verify_name
	#attr_accessor :emp_name, :emp_des
	validates_presence_of :emp_name,:emp_des, :message =>"can't be empty"
	has_one :Profile
	has_many :Article
private
	def ring
		puts"hello before save method called "
	end

	private
def check
# Strip everything in the number except digits

Date.today
end
private
def verify_name
	#debugger
	@employee = Employee.exists?(emp_name: "#{emp_name}")
	if(@employee)
		
			puts 'root' 
	end	
	#@employee =Employee.all
	#return @employee
end


end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_for_oauth(auth)
    find_or_create_by(uid: auth.uid, provider: auth.provider)
  end
end

app/models/member.rb
class Member < ActiveRecord::Base
has_belongs_to_many :team  #, touch: true
end

app/models/part.rb
class Part < ActiveRecord::Base
has_and_belongs_to_many :assemblies
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :Employee
end

app/models/team.rb
class Team < ActiveRecord::Base
has_and_belongs_to_many :members


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable, :lockable,
  #        :recoverable, :rememberable, :trackable,:confirmable, :validatable

#devise :omniauthable, :omniauth_providers => [:facebook]

devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
     :omniauthable, :omniauth_providers => [:digitalocean]

  def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
      end
  end
    
end

app/controllers/assemblies_controller.rb
  class AssembliesController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_assembly, only: [:show, :edit, :update, :destroy]

  # GET /assemblies
  # GET /assemblies.json
  def index
    @assemblies = Assembly.all
  end

  # GET /assemblies/1
  # GET /assemblies/1.json
  def show
  end

  # GET /assemblies/new
  def new
    byebug
    @part = Part.all
    @assembly = Assembly.new
  end

  # GET /assemblies/1/edit
  def edit
  end

  # POST /assemblies
  # POST /assemblies.json
  def create
    byebug
    @part = Part.find(params[:part_ids])
    @assembly = Assembly.new(assembly_params)
    respond_to do |format|
      if @assembly.save
        format.html { redirect_to @assembly, notice: 'Assembly was successfully created.' }
        format.json { render :show, status: :created, location: @assembly }
      else
        format.html { render :new }
        format.json { render json: @assembly.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assemblies/1
  # PATCH/PUT /assemblies/1.json
  def update
    respond_to do |format|
      if @assembly.update(assembly_params)
        format.html { redirect_to @assembly, notice: 'Assembly was successfully updated.' }
        format.json { render :show, status: :ok, location: @assembly }
      else
        format.html { render :edit }
        format.json { render json: @assembly.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assemblies/1
  # DELETE /assemblies/1.json
  def destroy
    @assembly.destroy
    respond_to do |format|
      format.html { redirect_to assemblies_url, notice: 'Assembly was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assembly
      @assembly = Assembly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assembly_params
      params.require(:assembly).permit(:name, :manufacturing_date,{part_ids:[]})
    end
end

app/helpers/assemblies_helper.rb
module AssembliesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/member_helper.rb
module MemberHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/assemblies/_form.html.erb
<%= form_for(@assembly) do |f| %>
  <% if @assembly.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@assembly.errors.count, "error") %> prohibited this assembly from being saved:</h2>

      <ul>
      <% @assembly.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :manufacturing_date %><br>
    <%= f.text_field :manufacturing_date %>
  </div>
  <div class="field">
    <%= f.label :Part_No %><br>
    <%= f.select :part_ids ,options_for_select(@part.map{|c| [c.name]}) %>
  </div>
  <div class="field">
    <%= f.label :All_Part_No %><br>
    <%= f.collection_check_boxes(:part_ids, @part, :id,:name) %>
    <%= f.hidden_field :part_id, value: params[:part_id] %>
  </div>
  <%= link_to "Update Unit", id:'btn-info',onclick:"clickAndDisable(this);" %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<script> 
   function clickAndDisable(link) {
    alert("hello");
     // disable subsequent clicks
     link.onclick = function(event) {
        event.preventDefault();
     }
   }   
</script>

app/views/assemblies/edit.html.erb
<h1>Editing Assembly</h1>

<%= render 'form' %>

<%= link_to 'Show', @assembly %> |
<%= link_to 'Back', assemblies_path %>

app/views/assemblies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Assemblies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Manufacturing date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assemblies.each do |assembly| %>
      <tr>
        <td><%= assembly.name %></td>
        <td><%= assembly.manufacturing_date %></td>
        <td><%= link_to 'Show', assembly %></td>
        <td><%= link_to 'Edit', edit_assembly_path(assembly) %></td>
        <td><%= link_to 'Destroy', assembly, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Assembly', new_assembly_path %>

app/views/assemblies/new.html.erb
<h1>New Assembly</h1>

<%= render 'form' %>

<%= link_to 'Back', assemblies_path %>

app/views/assemblies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @assembly.name %>
</p>

<p>
  <strong>Manufacturing date:</strong>
  <%= @assembly.manufacturing_date %>
</p>

<%= link_to 'Edit', edit_assembly_path(@assembly) %> |
<%= link_to 'Back', assemblies_path %>